---
title: "CLAMP(Climate Leaf Analysis Multivariate Programe)"
author: "気候と葉の多変量解析"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
documentclass: bxjsarticle
classoption: xelatex
papersize: a4paper
fontsize: 12pt
geometry: "top=14truemm,bottom=14truemm,left=20truemm,right=16truemm,nohead,nofoot"
output:
  html_document:
    toc: true
    toc_depth: 4
    number_sections: true
  word_document:
    toc: false
    toc_depth: 4
    keep_md: true
#    reference_docx: ./reference.docx
  pdf_document:
    latex_engine: xelatex
    toc: false
    toc_depth: 4
    fig_caption: true
    keep_tex: true
    template: MyTemplate.latex
---

```{r echo=FALSE,message=FALSE,comment=NA}
require(knitr)
require(rmarkdown)
knitr::opts_chunk$set(echo=FALSE,comment=NA, prompt=TRUE, message=FALSE, fig.height=12, fig.width=8)
#library(Rcmdr)
#library(car)
library(RcmdrMisc)
```
# モデル作成に使用したデータ

- 寒冷地のデータ("alpine nest")を除いた144のデータからなるサブセット(Physg3brcAZ , Met3brAZ)


```{r}
library(vegan)
library(investr)
library(xtable)
library(RcmdrMisc)
# 144
#leaves<- read.csv("./Physg3brcAZ.csv",row.names=1,check.names=F)
#climate<- read.csv("./Met3brAZ.csv",row.names=1,check.names=F)
climate<- readXL("Met3brAZ.xls", rownames = T, header = TRUE, na = "", sheet = 1, stringsAsFactors = FALSE)
leaves<- readXL("Physg3brcAZ.xls", rownames = T, header = TRUE, na = "", sheet = 1, stringsAsFactors = FALSE)
colnames(climate)<- c("MAT","WMMT","CMMT","GROWSEAS","GSP","MMGSP","3-WET","3-DRY","RH","SH","ENTHAL")
colnames(leaves)<- c("Lobed","No Teeth","Regular teeth","Close teeth","Round teeth","Acute teeth","Compound teeth","Nanophyll",
	"Leptophyll 1","Leptophyll 2","Microphyll 1","Microphyll 2","Microphyll 3","Mesophyll 1","Mesophyll 2",
	"Mesophyll 3","Emarginate apex","Round apex","Acute apex","Attenuate apex","Cordate base","Round base",
	"Acute base","L:W <1:1","L:W 1-2:1","L:W 2-3:1","L:W 3-4:1","L:W >4:1","Obovate","Elliptic","Ovate")
res <- cca(leaves~.,climate) 
```

## Modelの分散分析

```{r, results = "asis", echo = FALSE}
print(xtable(anova(res)), comment = FALSE)
```

## 各説明変数毎の分散分析


```{r, results = "asis", echo = FALSE}
print(xtable(anova(res,by="term",step=200)), comment = FALSE)
```

## 変数軸について調べる


```{r, results = "asis", echo = FALSE}
print(xtable(anova(res,by="axis",step=200)), comment = FALSE)
```

```{r}
EBS<- summary(res)[[4]][,1:4]
# Site Biplot Scores
SBS<- summary(res)[[2]][,1:4]
#
co<- NULL
estclim<- list()
for (num in 1:11){
x<- NULL
for (i in 1:nrow(SBS)){
	x<- c(x,sum(EBS[num,]*SBS[i,])/sqrt(sum(EBS[num,]^2)))
}
#fm<-nls(climate[,num] ~a+b*x+c*x^2,start=c(a=1,b=1,c=-1)) 
df<- data.frame(x=x,y=climate[,num])
fm<-nls(y ~a+b*x+c*x^2,start=c(a=1,b=1,c=-1),data=df) 
estclim[[num]]<- list(fm,x)
co<- rbind(co,rev(coef(summary(fm))[,1]))
}
names(estclim)<- colnames(climate)
```

```{r, results = "asis",  echo = FALSE}
#print(xtable(co,digits=4 ),comment = FALSE)
```

## $y=a+b*x+c*x^2$
### 各々の変数のパラメータ推定値、標準誤差、t値、p値


```{r}
i=1
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=2
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```

\clearpage
```{r}
i=3
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=4
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=5
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=6
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```
\clearpage

```{r}
i=7
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=8
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=9
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```


```{r}
i=10
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```
\clearpage

```{r}
i=11
cat(paste0(names(estclim)[i]))
cat("\n")
	mat_model = summary(estclim[[i]][[1]])$coefficients
	### generate coefficients, se, t-stat and p values 
	df_model = as.data.frame(mat_model)
	colnames(df_model) <- c("Coef.", "Std. error", "t-stat.", "p")
	mat <- data.frame(t(df_model))
	kable(mat,digits=3)
```

## 実測値と予測値との相関係数


```{r}
COR<- NULL
for (i in 1:11){
	COR<- c(COR,round(cor(climate[,i],predict(estclim[[i]][[1]])),3))
}
COR<- data.frame("Correlation coefficient"=COR)
rownames(COR)<- colnames(climate)
```

```{r, results = "asis",  echo = FALSE}
print(xtable(COR,digits=3 ), comment = FALSE)
```

